name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby!
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      - name: run tests
        run: rake test